/**
 * FR-156 — Shared prototype iframe component.
 *
 * Single source of truth for rendering a prototype attachment inline. Used by
 * both Spec Review (PrototypePanel) and UAT Review (UATChecklistItem's
 * PrototypePreviewInline) so the two surfaces render identically — same CSP,
 * same sandbox, same stale-content fallback.
 *
 * Behaviour:
 *  - Stale-content detection: if `content` starts with raw Mermaid markup
 *    (pre-FR-156 producer output), render a degraded fallback with the raw
 *    markup in a `<pre>` and a Regenerate button. Do NOT iframe-render.
 *  - Sandbox: `allow-scripts` only — no `allow-same-origin` so the iframe
 *    cannot read the parent context's cookies/localStorage/DOM.
 *  - CSP injection: defensive — adds a CSP meta tag to the iframe `srcDoc`
 *    if the producer didn't include one. Mode picked from `prototypeType`.
 *
 * See contracts/prototype-iframe.md for the full contract.
 */

import { useState } from 'react';

const RAW_MERMAID_PREFIX =
  /^\s*(flowchart\b|sequenceDiagram\b|gantt\b|pie\b|classDiagram\b|stateDiagram\b)/;

const STRICT_CSP = "default-src 'none'; img-src 'self' data:; style-src 'unsafe-inline'";
const RELAXED_CSP =
  "default-src 'self' https:; img-src 'self' https: data:; style-src 'self' https: 'unsafe-inline'; script-src 'self' https:";

export type PrototypeContentType = 'ui' | 'flowchart' | 'sequence' | 'process' | 'unknown';

interface PrototypeIframeProps {
  content: string;
  prototypeType: PrototypeContentType | string;
  featureCode: string;
  onRegenerate?: () => void;
  title?: string;
}

function isStaleRawMarkup(content: string): boolean {
  return RAW_MERMAID_PREFIX.test(content);
}

function getCspMode(prototypeType: string): 'strict' | 'relaxed' {
  if (prototypeType === 'ui' || prototypeType === 'process' || prototypeType === 'ui_mockup') {
    return 'relaxed';
  }
  return 'strict';
}

function injectCspIfMissing(content: string, mode: 'strict' | 'relaxed'): string {
  if (content.includes('http-equiv="Content-Security-Policy"')) return content;
  const policy = mode === 'relaxed' ? RELAXED_CSP : STRICT_CSP;
  const meta = `<meta http-equiv="Content-Security-Policy" content="${policy}" />`;
  if (content.includes('<head>')) {
    return content.replace('<head>', `<head>\n  ${meta}`);
  }
  if (content.includes('<html')) {
    return content.replace(/<html([^>]*)>/, `<html$1>\n<head>${meta}</head>`);
  }
  return `<!DOCTYPE html><html><head>${meta}</head><body>${content}</body></html>`;
}

async function copyRegenerateCommand(featureCode: string): Promise<boolean> {
  const cmd = `\\generate-prototype ${featureCode}`;
  try {
    await navigator.clipboard.writeText(cmd);
    return true;
  } catch {
    return false;
  }
}

export function PrototypeIframe({
  content,
  prototypeType,
  featureCode,
  onRegenerate,
  title,
}: PrototypeIframeProps) {
  const [copied, setCopied] = useState(false);

  if (!content || content.trim().length === 0) {
    return null;
  }

  if (isStaleRawMarkup(content)) {
    return (
      <StaleFallback
        content={content}
        featureCode={featureCode}
        onRegenerate={onRegenerate}
        copied={copied}
        setCopied={setCopied}
      />
    );
  }

  const cspMode = getCspMode(prototypeType);
  const srcDoc = injectCspIfMissing(content, cspMode);
  const iframeTitle = title ?? `Prototype for ${featureCode}`;

  return (
    <iframe
      srcDoc={srcDoc}
      sandbox="allow-scripts"
      title={iframeTitle}
      data-testid="prototype-iframe"
      data-csp-mode={cspMode}
      className="w-full bg-white"
      style={{ border: 'none', minHeight: '320px' }}
    />
  );
}

interface StaleFallbackProps {
  content: string;
  featureCode: string;
  onRegenerate?: () => void;
  copied: boolean;
  setCopied: (v: boolean) => void;
}

function StaleFallback({
  content,
  featureCode,
  onRegenerate,
  copied,
  setCopied,
}: StaleFallbackProps) {
  const handleClick = async () => {
    if (onRegenerate) {
      onRegenerate();
      return;
    }
    const ok = await copyRegenerateCommand(featureCode);
    if (ok) {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  };

  return (
    <div
      data-testid="prototype-iframe-stale"
      className="px-3 py-2 text-xs text-amber-800 bg-amber-50 border border-amber-200 rounded-md max-w-3xl"
    >
      <div className="font-medium mb-1">Prototype needs regeneration</div>
      <div className="text-amber-700 mb-2">
        This prototype was generated by an older renderer and needs regenerating to render inline.
      </div>
      <pre className="text-[11px] bg-white border border-amber-100 rounded p-2 max-h-48 overflow-auto whitespace-pre-wrap">
        {content.slice(0, 1500)}
        {content.length > 1500 ? '\n...' : ''}
      </pre>
      <button
        type="button"
        onClick={handleClick}
        className="mt-2 px-2.5 py-1 text-xs font-medium text-amber-800 bg-amber-100 border border-amber-300 rounded hover:bg-amber-200 transition-colors"
      >
        {copied ? '✓ Command copied' : '↻ Regenerate prototype'}
      </button>
    </div>
  );
}
